---

- name: Update the instance and create a test file
  hosts: all
  become: yes
  become_user: ec2-user

  tasks:
    - name: Exécuter une commande shell
      shell: ansible-playbook website.yml
      register: resultat_commande

    - name: Afficher la sortie de la commande
      debug:
        var: resultat_commande.stdout_lines
